dataset: figraph
time_column: year
label_column: label
subsets:
  - id: 0
    train_years: [2014, 2015, 2016]
    val_years:   [2017]
    test_years:  [2018]
    counts: {train: 8580, val: 3503, test: 3596}
  - id: 1
    train_years: [2014, 2015, 2016, 2017]
    val_years:   [2018]
    test_years:  [2019]
    counts: {train: 12083, val: 3596, test: 3815}
  - id: 2
    train_years: [2014, 2015, 2016, 2017, 2018]
    val_years:   [2019]
    test_years:  [2020]
    counts: {train: 15679, val: 3815, test: 4269}
  - id: 3
    train_years: [2014, 2015, 2016, 2017, 2018, 2019]
    val_years:   [2020]
    test_years:  [2021]
    counts: {train: 19494, val: 4269, test: 4769}
  - id: 4
    train_years: [2014, 2015, 2016, 2017, 2018, 2019, 2020]
    val_years:   [2021]
    test_years:  [2022]
    counts: {train: 23763, val: 4769, test: 5132}
